### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [KseniiaBond/grid-template#1]
1)
Присуствует незначительное несоответствие макету, проверьте и исправьте для активного элемента
![image](https://user-images.githubusercontent.com/8464662/151826278-69196e07-00e3-4c54-8d0a-282f577bb812.png)

2)
Присуствует незначительное несоответствие макету, проверьте и исправьте.
![image](https://user-images.githubusercontent.com/8464662/151826430-92f0c03a-c6ee-4319-a5a8-26d592a8d3fe.png)

3)
Отступы не соответствуют поставленной задаче.
![image](https://user-images.githubusercontent.com/8464662/151826659-be1d94af-0f1c-418d-b906-5d4621872593.png)

**Comment by KseniiaBond** [comment]
Исправлено.
По 2 пункту - Я ориентировалась на макет, который использовала для pixel perfect (png формат). Он отличается от макета дизайнера.

**Comment by Alecto** [comment]
2 - не исправлено

**Comment by KseniiaBond** [comment]
исправила паддинги

**Comment by Alecto** [comment]
Для сдачи проекта требуются две ссылки:
1 - на страницу github pages.
2 - на страницу репозитория.
Все описание есть в документации, в разделе "Критерии сдачи проекта".


чт, 3 лют. 2022 р. о 22:49 KseniiaBond ***@***.***> пише:

**Comment by Alecto** [comment]
причем здесь паддинги? нет никакого соответствия секции
2 - не исправлено

**Comment by KseniiaBond** [comment]
исправила

![pp](https://user-images.githubusercontent.com/94927392/152701639-0f8b1699-c90a-4921-9feb-9911a6c402e4.png)
